import tokens from '../tokens'

export default {
  [tokens.wBTC.symbol.toLowerCase()]: tokens.wBTC.coinGeckoId,
  [tokens.WETH.symbol.toLowerCase()]: tokens.WETH.coinGeckoId,
  [tokens.INJ.symbol.toLowerCase()]: tokens.INJ.coinGeckoId,
  [tokens.USDT.symbol.toLowerCase()]: tokens.USDT.coinGeckoId,
  [tokens.USDC.symbol.toLowerCase()]: tokens.USDC.coinGeckoId,
  [tokens.GRT.symbol.toLowerCase()]: tokens.GRT.coinGeckoId,
  [tokens.SNX.symbol.toLowerCase()]: tokens.SNX.coinGeckoId,
  [tokens.DAI.symbol.toLowerCase()]: tokens.DAI.coinGeckoId,
  [tokens.BNB.symbol.toLowerCase()]: tokens.BNB.coinGeckoId,
  [tokens.AAVE.symbol.toLowerCase()]: tokens.AAVE.coinGeckoId,
  [tokens.YFI.symbol.toLowerCase()]: tokens.YFI.coinGeckoId,
  [tokens.COMP.symbol.toLowerCase()]: tokens.COMP.coinGeckoId,
  [tokens.ZRX.symbol.toLowerCase()]: tokens.ZRX.coinGeckoId,
  [tokens.MATIC.symbol.toLowerCase()]: tokens.MATIC.coinGeckoId,
  [tokens.UNI.symbol.toLowerCase()]: tokens.UNI.coinGeckoId,
  [tokens.LINK.symbol.toLowerCase()]: tokens.LINK.coinGeckoId,
  [tokens.SUSHI.symbol.toLowerCase()]: tokens.SUSHI.coinGeckoId,
  [tokens.AXS.symbol.toLowerCase()]: tokens.AXS.coinGeckoId,
  [tokens['1INCH'].symbol.toLowerCase()]: tokens['1INCH'].coinGeckoId,
  [tokens.BAT.symbol.toLowerCase()]: tokens.BAT.coinGeckoId,
  [tokens.BUSD.symbol.toLowerCase()]: tokens.BUSD.coinGeckoId,
  [tokens.CEL.symbol.toLowerCase()]: tokens.CEL.coinGeckoId,
  [tokens.CELL.symbol.toLowerCase()]: tokens.CELL.coinGeckoId,
  [tokens.CHZ.symbol.toLowerCase()]: tokens.CHZ.coinGeckoId,
  [tokens.DEFI5.symbol.toLowerCase()]: tokens.DEFI5.coinGeckoId,
  [tokens.ENJ.symbol.toLowerCase()]: tokens.ENJ.coinGeckoId,
  [tokens.EVAI.symbol.toLowerCase()]: tokens.EVAI.coinGeckoId,
  [tokens.FTM.symbol.toLowerCase()]: tokens.FTM.coinGeckoId,
  [tokens.HT.symbol.toLowerCase()]: tokens.HT.coinGeckoId,
  [tokens.NEXO.symbol.toLowerCase()]: tokens.NEXO.coinGeckoId,
  [tokens.NOIA.symbol.toLowerCase()]: tokens.NOIA.coinGeckoId,
  [tokens.OCEAN.symbol.toLowerCase()]: tokens.OCEAN.coinGeckoId,
  [tokens.PAXG.symbol.toLowerCase()]: tokens.PAXG.coinGeckoId,
  [tokens.POOL.symbol.toLowerCase()]: tokens.POOL.coinGeckoId,
  [tokens.RUNE.symbol.toLowerCase()]: tokens.RUNE.coinGeckoId,
  [tokens.SHIB.symbol.toLowerCase()]: tokens.SHIB.coinGeckoId,
  [tokens.STARS.symbol.toLowerCase()]: tokens.STARS.coinGeckoId,
  [tokens.STT.symbol.toLowerCase()]: tokens.STT.coinGeckoId,
  [tokens.SWAP.symbol.toLowerCase()]: tokens.SWAP.coinGeckoId,
  [tokens.UMA.symbol.toLowerCase()]: tokens.UMA.coinGeckoId,
  [tokens.UTK.symbol.toLowerCase()]: tokens.UTK.coinGeckoId,
  [tokens.ATOM.symbol.toLowerCase()]: tokens.ATOM.coinGeckoId,
  [tokens.UPHOTON.symbol.toLowerCase()]: tokens.UPHOTON.coinGeckoId,
} as Record<string, string>
