import tokens from '../tokens'

export default {
  [tokens.wBTC.symbol.toLowerCase()]: tokens.wBTC.coinGeckoId,
  [tokens.WETH.symbol.toLowerCase()]: tokens.WETH.coinGeckoId,
  [tokens.INJ.symbol.toLowerCase()]: tokens.INJ.coinGeckoId,
  [tokens.USDT.symbol.toLowerCase()]: tokens.USDT.coinGeckoId,
  [tokens.USDC.symbol.toLowerCase()]: tokens.USDC.coinGeckoId,
  [tokens.GRT.symbol.toLowerCase()]: tokens.GRT.coinGeckoId,
  [tokens.SNX.symbol.toLowerCase()]: tokens.SNX.coinGeckoId,
  [tokens.DAI.symbol.toLowerCase()]: tokens.DAI.coinGeckoId,
  [tokens.BNB.symbol.toLowerCase()]: tokens.BNB.coinGeckoId,
  [tokens.AAVE.symbol.toLowerCase()]: tokens.AAVE.coinGeckoId,
  [tokens.YFI.symbol.toLowerCase()]: tokens.YFI.coinGeckoId,
  [tokens.COMP.symbol.toLowerCase()]: tokens.COMP.coinGeckoId,
  [tokens.ZRX.symbol.toLowerCase()]: tokens.ZRX.coinGeckoId,
  [tokens.MATIC.symbol.toLowerCase()]: tokens.MATIC.coinGeckoId,
  [tokens.UNI.symbol.toLowerCase()]: tokens.UNI.coinGeckoId,
  [tokens.LINK.symbol.toLowerCase()]: tokens.LINK.coinGeckoId,
  [tokens.SUSHI.symbol.toLowerCase()]: tokens.SUSHI.coinGeckoId,
  [tokens.AXS.symbol.toLowerCase()]: tokens.AXS.coinGeckoId,
  [tokens['1INCH'].address.toLowerCase()]: tokens['1INCH'].coinGeckoId,
  [tokens.BAT.address.toLowerCase()]: tokens.BAT.coinGeckoId,
  [tokens.BUSD.address.toLowerCase()]: tokens.BUSD.coinGeckoId,
  [tokens.CEL.address.toLowerCase()]: tokens.CEL.coinGeckoId,
  [tokens.CELL.address.toLowerCase()]: tokens.CELL.coinGeckoId,
  [tokens.CHZ.address.toLowerCase()]: tokens.CHZ.coinGeckoId,
  [tokens.DEFI5.address.toLowerCase()]: tokens.DEFI5.coinGeckoId,
  [tokens.ENJ.address.toLowerCase()]: tokens.ENJ.coinGeckoId,
  [tokens.EVAI.address.toLowerCase()]: tokens.EVAI.coinGeckoId,
  [tokens.FTM.address.toLowerCase()]: tokens.FTM.coinGeckoId,
  [tokens.HT.address.toLowerCase()]: tokens.HT.coinGeckoId,
  [tokens.NEXO.address.toLowerCase()]: tokens.NEXO.coinGeckoId,
  [tokens.NOIA.address.toLowerCase()]: tokens.NOIA.coinGeckoId,
  [tokens.OCEAN.address.toLowerCase()]: tokens.OCEAN.coinGeckoId,
  [tokens.PAXG.address.toLowerCase()]: tokens.PAXG.coinGeckoId,
  [tokens.POOL.address.toLowerCase()]: tokens.POOL.coinGeckoId,
  [tokens.RUNE.address.toLowerCase()]: tokens.RUNE.coinGeckoId,
  [tokens.SHIB.address.toLowerCase()]: tokens.SHIB.coinGeckoId,
  [tokens.STARS.address.toLowerCase()]: tokens.STARS.coinGeckoId,
  [tokens.STT.address.toLowerCase()]: tokens.STT.coinGeckoId,
  [tokens.SWAP.address.toLowerCase()]: tokens.SWAP.coinGeckoId,
  [tokens.UMA.address.toLowerCase()]: tokens.UMA.coinGeckoId,
  [tokens.UTK.address.toLowerCase()]: tokens.UTK.coinGeckoId,
} as Record<string, string>
