packages:
  - 'packages/*'
  - 'packages/wallets/*'
  - 'protoV2/*/proto-ts'

catalog:
  # Core libraries
  viem: ^2.41.2
  ethers: ^6.16.0
  axios: ^1.13.2

  # Cosmos ecosystem
  '@cosmjs/amino': 0.33.0
  '@cosmjs/proto-signing': 0.33.0
  '@cosmjs/stargate': 0.33.0
  '@keplr-wallet/types': ^0.12.296

  # Utilities
  http-status-codes: ^2.3.0
  eip1193-provider: ^1.0.1
  bignumber.js: ^9.3.1
  rxjs: 7.8.2

  # Cryptography
  '@noble/curves': ^1.9.0
  '@noble/hashes': ^1.8.0
  '@scure/base': ^1.2.6
