"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MsgStatus = exports.MsgType = exports.ChainId = exports.EthereumChainId = void 0;
var EthereumChainId;
(function (EthereumChainId) {
    EthereumChainId[EthereumChainId["Mainnet"] = 1] = "Mainnet";
    EthereumChainId[EthereumChainId["Ropsten"] = 3] = "Ropsten";
    EthereumChainId[EthereumChainId["Rinkeby"] = 4] = "Rinkeby";
    EthereumChainId[EthereumChainId["Goerli"] = 5] = "Goerli";
    EthereumChainId[EthereumChainId["Kovan"] = 42] = "Kovan";
    EthereumChainId[EthereumChainId["Sepolia"] = 11155111] = "Sepolia";
    EthereumChainId[EthereumChainId["Injective"] = 888] = "Injective";
    EthereumChainId[EthereumChainId["Ganache"] = 1337] = "Ganache";
    EthereumChainId[EthereumChainId["HardHat"] = 31337] = "HardHat";
})(EthereumChainId = exports.EthereumChainId || (exports.EthereumChainId = {}));
var ChainId;
(function (ChainId) {
    ChainId["Mainnet"] = "injective-1";
    ChainId["Testnet"] = "injective-888";
    ChainId["Devnet"] = "injective-777";
})(ChainId = exports.ChainId || (exports.ChainId = {}));
var MsgType;
(function (MsgType) {
    MsgType["MsgExec"] = "cosmos.authz.v1beta1.MsgExec";
    MsgType["MsgGrant"] = "cosmos.authz.v1beta1.MsgGrant";
    MsgType["MsgRevoke"] = "cosmos.authz.v1beta1.MsgRevoke";
    MsgType["MsgSend"] = "cosmos.bank.v1beta1.MsgSend";
    MsgType["MsgWithdrawDelegatorReward"] = "cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward";
    MsgType["MsgGrantAllowance"] = "cosmos.feegrant.v1beta1.MsgGrantAllowance";
    MsgType["MsgRevokeAllowance"] = "cosmos.feegrant.v1beta1.MsgRevokeAllowance";
    MsgType["MsgDepositCosmos"] = "cosmos.gov.v1beta1.MsgDeposit";
    MsgType["MsgSubmitProposal"] = "cosmos.gov.v1beta1.MsgSubmitProposal";
    MsgType["MsgVote"] = "cosmos.gov.v1beta1.MsgVote";
    MsgType["MsgUnjail"] = "cosmos.slashing.v1beta1.MsgUnjail";
    MsgType["MsgBeginRedelegate"] = "cosmos.staking.v1beta1.MsgBeginRedelegate";
    MsgType["MsgCreateValidator"] = "cosmos.staking.v1beta1.MsgCreateValidator";
    MsgType["MsgDelegate"] = "cosmos.staking.v1beta1.MsgDelegate";
    MsgType["MsgEditValidator"] = "cosmos.staking.v1beta1.MsgEditValidator";
    MsgType["MsgUndelegate"] = "cosmos.staking.v1beta1.MsgUndelegate";
    MsgType["MsgCancelUnbondingDelegation"] = "cosmos.staking.v1beta1.MsgCancelUnbondingDelegation";
    MsgType["MsgExecuteContract"] = "cosmwasm.wasm.v1.MsgExecuteContract";
    MsgType["MsgInstantiateContract"] = "cosmwasm.wasm.v1.MsgInstantiateContract";
    MsgType["MsgInstantiateContract2"] = "cosmwasm.wasm.v1.MsgInstantiateContract2";
    MsgType["MsgMigrateContract"] = "cosmwasm.wasm.v1.MsgMigrateContract";
    MsgType["MsgStoreCode"] = "cosmwasm.wasm.v1.MsgStoreCode";
    MsgType["MsgUpdateAdmin"] = "cosmwasm.wasm.v1.MsgUpdateAdmin";
    MsgType["MsgTransfer"] = "ibc.applications.transfer.v1.MsgTransfer";
    MsgType["MsgAcknowledgement"] = "ibc.core.channel.v1.MsgAcknowledgement";
    MsgType["MsgChannelOpenAck"] = "ibc.core.channel.v1.MsgChannelOpenAck";
    MsgType["MsgChannelOpenConfirm"] = "ibc.core.channel.v1.MsgChannelOpenConfirm";
    MsgType["MsgChannelOpenInit"] = "ibc.core.channel.v1.MsgChannelOpenInit";
    MsgType["MsgChannelOpenTry"] = "ibc.core.channel.v1.MsgChannelOpenTry";
    MsgType["MsgRecvPacket"] = "ibc.core.channel.v1.MsgRecvPacket";
    MsgType["MsgTimeout"] = "ibc.core.channel.v1.MsgTimeout";
    MsgType["MsgCreateClient"] = "ibc.core.client.v1.MsgCreateClient";
    MsgType["MsgUpdateClient"] = "ibc.core.client.v1.MsgUpdateClient";
    MsgType["MsgConnectionOpenAck"] = "ibc.core.connection.v1.MsgConnectionOpenAck";
    MsgType["MsgConnectionOpenConfirm"] = "ibc.core.connection.v1.MsgConnectionOpenConfirm";
    MsgType["MsgConnectionOpenInit"] = "ibc.core.connection.v1.MsgConnectionOpenInit";
    MsgType["MsgConnectionOpenTry"] = "ibc.core.connection.v1.MsgConnectionOpenTry";
    MsgType["MsgBid"] = "injective.auction.v1beta1.MsgBid";
    MsgType["MsgAdminUpdateBinaryOptionsMarket"] = "injective.exchange.v1beta1.MsgAdminUpdateBinaryOptionsMarket";
    MsgType["MsgBatchCancelDerivativeOrders"] = "injective.exchange.v1beta1.MsgBatchCancelDerivativeOrders";
    MsgType["MsgBatchCancelSpotOrders"] = "injective.exchange.v1beta1.MsgBatchCancelSpotOrders";
    MsgType["MsgBatchCreateDerivativeLimitOrders"] = "injective.exchange.v1beta1.MsgBatchCreateDerivativeLimitOrders";
    MsgType["MsgBatchCreateSpotLimitOrders"] = "injective.exchange.v1beta1.MsgBatchCreateSpotLimitOrders";
    MsgType["MsgBatchUpdateOrders"] = "injective.exchange.v1beta1.MsgBatchUpdateOrders";
    MsgType["MsgCancelBinaryOptionsOrder"] = "injective.exchange.v1beta1.MsgCancelBinaryOptionsOrder";
    MsgType["MsgCancelDerivativeOrder"] = "injective.exchange.v1beta1.MsgCancelDerivativeOrder";
    MsgType["MsgCancelSpotOrder"] = "injective.exchange.v1beta1.MsgCancelSpotOrder";
    MsgType["MsgCreateBinaryOptionsLimitOrder"] = "injective.exchange.v1beta1.MsgCreateBinaryOptionsLimitOrder";
    MsgType["MsgCreateBinaryOptionsMarketOrder"] = "injective.exchange.v1beta1.MsgCreateBinaryOptionsMarketOrder";
    MsgType["MsgCreateDerivativeLimitOrder"] = "injective.exchange.v1beta1.MsgCreateDerivativeLimitOrder";
    MsgType["MsgCreateDerivativeMarketOrder"] = "injective.exchange.v1beta1.MsgCreateDerivativeMarketOrder";
    MsgType["MsgLiquidatePosition"] = "injective.exchange.v1beta1.MsgLiquidatePosition";
    MsgType["MsgCreateSpotLimitOrder"] = "injective.exchange.v1beta1.MsgCreateSpotLimitOrder";
    MsgType["MsgCreateSpotMarketOrder"] = "injective.exchange.v1beta1.MsgCreateSpotMarketOrder";
    MsgType["MsgDeposit"] = "injective.exchange.v1beta1.MsgDeposit";
    MsgType["MsgExternalTransfer"] = "injective.exchange.v1beta1.MsgExternalTransfer";
    MsgType["MsgIncreasePositionMargin"] = "injective.exchange.v1beta1.MsgIncreasePositionMargin";
    MsgType["MsgInstantBinaryOptionsMarketLaunch"] = "injective.exchange.v1beta1.MsgInstantBinaryOptionsMarketLaunch";
    MsgType["MsgInstantPerpetualMarketLaunch"] = "injective.exchange.v1beta1.MsgInstantPerpetualMarketLaunch";
    MsgType["MsgInstantSpotMarketLaunch"] = "injective.exchange.v1beta1.MsgInstantSpotMarketLaunch";
    MsgType["MsgReclaimLockedFunds"] = "injective.exchange.v1beta1.MsgReclaimLockedFunds";
    MsgType["MsgRewardsOptOut"] = "injective.exchange.v1beta1.MsgRewardsOptOut";
    MsgType["MsgSubaccountTransfer"] = "injective.exchange.v1beta1.MsgSubaccountTransfer";
    MsgType["MsgWithdraw"] = "injective.exchange.v1beta1.MsgWithdraw";
    MsgType["MsgCreateInsuranceFund"] = "injective.insurance.v1beta1.MsgCreateInsuranceFund";
    MsgType["MsgRequestRedemption"] = "injective.insurance.v1beta1.MsgRequestRedemption";
    MsgType["MsgUnderwrite"] = "injective.insurance.v1beta1.MsgUnderwrite";
    MsgType["MsgConfirmBatch"] = "injective.peggy.v1.MsgConfirmBatch";
    MsgType["MsgDepositClaim"] = "injective.peggy.v1.MsgDepositClaim";
    MsgType["MsgERC20DeployedClaim"] = "injective.peggy.v1.MsgERC20DeployedClaim";
    MsgType["MsgRequestBatch"] = "injective.peggy.v1.MsgRequestBatch";
    MsgType["MsgSendToEth"] = "injective.peggy.v1.MsgSendToEth";
    MsgType["MsgSetOrchestratorAddresses"] = "injective.peggy.v1.MsgSetOrchestratorAddresses";
    MsgType["MsgValsetConfirm"] = "injective.peggy.v1.MsgValsetConfirm";
    MsgType["MsgValsetUpdatedClaim"] = "injective.peggy.v1.MsgValsetUpdatedClaim";
    MsgType["MsgWithdrawClaim"] = "injective.peggy.v1.MsgWithdrawClaim";
    MsgType["MsgBurn"] = "injective.tokenfactory.v1beta1.MsgBurn";
    MsgType["MsgMint"] = "injective.tokenfactory.v1beta1.MsgMint";
    MsgType["MsgCreateDenom"] = "injective.tokenfactory.v1beta1.MsgCreateDenom";
    MsgType["MsgExecuteContractCompat"] = "injective.wasmx.v1.MsgExecuteContractCompat";
    MsgType["MsgPrivilegedExecuteContract"] = "injective.exchange.v1beta1.MsgPrivilegedExecuteContract";
    MsgType["MsgMultiSend"] = "cosmos.bank.v1beta1.MsgMultiSend";
})(MsgType = exports.MsgType || (exports.MsgType = {}));
var MsgStatus;
(function (MsgStatus) {
    MsgStatus["Success"] = "success";
    MsgStatus["Fail"] = "fail";
})(MsgStatus = exports.MsgStatus || (exports.MsgStatus = {}));
//# sourceMappingURL=enums.js.map