import { TokenMeta } from '../../types'

export default {
  vMOMO: {
    name: 'Momoshiki',
    logo: 'momoshiki.svg',
    symbol: 'vMOMO',
    decimals: 18,
    cw20Address: '',
    coinGeckoId: '',
  },
  vKIN: {
    name: 'Kinshiki',
    logo: 'kinshiki.svg',
    symbol: 'vKIN',
    decimals: 18,
    cw20Address: '',
    coinGeckoId: '',
  },
  vTON: {
    name: 'Toneri',
    logo: 'toneri.svg',
    symbol: 'vTON',
    decimals: 18,
    cw20Address: '',
    coinGeckoId: '',
  },
  vNAR: {
    name: 'Naruto',
    logo: 'naruto.svg',
    symbol: 'vNAR',
    decimals: 18,
    cw20Address: '',
    coinGeckoId: '',
  },
  vMAD: {
    name: 'Madara',
    logo: 'madara.svg',
    symbol: 'vMAD',
    decimals: 18,
    cw20Address: '',
    coinGeckoId: '',
  },
  vMIN: {
    name: 'Minato',
    logo: 'minato.svg',
    symbol: 'vMAD',
    decimals: 18,
    cw20Address: '',
    coinGeckoId: '',
  },
  vSPOT: {
    name: 'Spot Vault',
    logo: 'minato.svg',
    symbol: 'vSPOT',
    decimals: 18,
    cw20Address: '',
    coinGeckoId: '',
  },
  vDERI: {
    name: 'Derivative Vault',
    logo: 'minato.svg',
    symbol: 'vDERI',
    decimals: 18,
    cw20Address: '',
    coinGeckoId: '',
  },
} as Record<string, TokenMeta>
