export default {
  'channel-1': { chainA: 'Injective', chainB: 'CosmosHub' },
  'channel-220': { chainA: 'CosmosHub', chainB: 'Injective' },
  'channel-83': { chainA: 'Injective', chainB: 'Evmos' },
  'channel-8': { chainA: 'Injective', chainB: 'Osmosis' },
  'channel-122': { chainA: 'Osmosis', chainB: 'Injective' },
  'channel-4': { chainA: 'Injective', chainB: 'Terra' },
  'channel-17': { chainA: 'Terra', chainB: 'Injective' },
  'channel-84': { chainA: 'Injective', chainB: 'Axelar' },
  'channel-82': { chainA: 'Injective', chainB: 'Persistence' },
  'channel-41': { chainA: 'Persistence', chainB: 'Injective' },
  'channel-76': { chainA: 'Injective', chainB: 'Chihuahua' },
  'channel-12': { chainA: 'Chihuahua', chainB: 'Injective' },
  'channel-88': { chainA: 'Injective', chainB: 'Secret Network' },
  'channel-23': { chainA: 'Secret Network', chainB: 'Injective' },
  'channel-78': { chainA: 'Injective', chainB: 'Juno' },
  'channel-59': { chainA: 'Juno', chainB: 'Injective' },
}
