name: Publish canary branch

on:
  push:
    branches-ignore:
      - master
      - dev

jobs:
  publish-canary:
    runs-on: ubuntu-latest
    permissions: write-all
    if: ${{ contains(github.event.head_commit.message, 'canary') }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Using Node from .nvmrc
        uses: useblacksmith/setup-node@v5
        with:
          node-version-file: '.nvmrc'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Set up Git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Build dependencies
        run: |
          node etc/bootstrapEnv
          pnpm install
          pnpm build

      - name: 'Setup npm'
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          # Tell Git to ignore this temporary change
          git update-index --assume-unchanged .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Version packages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pnpm exec lerna version prerelease --preid alpha --force-publish --force-git-tag --no-changelog --yes --no-push

      - name: Publish to npm
        run: |
          pnpm publish -r --access public --tag alpha --no-git-checks --report-summary

      - name: Push tags to git
        run: |
          git push --follow-tags

      - name: 'Broadcast published versions on Slack'
        run: node etc/slack.cjs --api=$SLACK_API --actor=$GIT_ACTOR --commit-message=$GIT_LATEST_COMMIT_MESSAGE
        env:
          GIT_ACTOR: ${{ github.actor }}
          SLACK_API: ${{ secrets.SLACK_API }}
          GIT_LATEST_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
