name: Publish stable

on:
  push:
    branches:
      - master

jobs:
  publish:
    if: false # temporary disabled
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: 'Use NodeJS 24'
        uses: actions/setup-node@v4
        with:
          node-version: '24.4.0'

      - name: 'Install pnpm'
        run: npm install -g pnpm

      - name: 'Setup pnpm global bin directory'
        run: |
          mkdir -p ~/.pnpm-global
          pnpm config set global-bin-dir ~/.pnpm-global
          echo "$HOME/.pnpm-global" >> $GITHUB_PATH

      - name: 'Setup lerna@8.2.3'
        run: pnpm install lerna@8.2.3 -g

      - name: Set up Git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Build dependencies
        run: |
          lerna clean --yes
          node etc/bootstrapEnv
          pnpm install
          pnpm build

      - name: Setup npm
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          # Tell Git to ignore this temporary change
          git update-index --assume-unchanged .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Version and publish
        run: |
          lerna version patch --conventional-commits --conventional-graduate --force-git-tag --yes
          lerna publish from-git --force-git-tag --dist-tag latest --yes --summary-file
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: 'Broadcast published versions on Slack'
        run: node etc/slack --api=$SLACK_API --actor=$GIT_ACTOR --commit-message=$GIT_LATEST_COMMIT_MESSAGE
        env:
          GIT_ACTOR: ${{ github.actor }}
          SLACK_API: ${{ secrets.SLACK_API }}
          GIT_LATEST_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

      - name: Merge master -> dev
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: dev
          github_token: ${{ secrets.GH_TOKEN }}
