name: Test gh actions

on:
  push:
    branches:
      - feat/test-gh-actions

jobs:
  publish:
    if: true
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout # Download code from the repository
        uses: actions/checkout@v2 # Public action
        with:
          fetch-depth: 0 # Checkout all branches and tags

      - name: 'Use NodeJS 18' # Setup node using version 14
        uses: actions/setup-node@v2 # Public action
        with:
          node-version: '18.17.0'

      - name: Setup lerna@6.6.1
        run: yarn global add lerna@6.6.1 --ignore-engines

      - name: Set up Git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Build dependencies
        run: |
          lerna clean --yes
          node etc/bootstrapEnv
          yarn install --ignore-engines
          yarn build
